CREATE TABLE WROX_USER (
	USER_ID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
	USERNAME VARCHAR(20) NOT NULL,
	PASSWORD CHAR(40) NOT NULL,
	EMAL_ADDR VARCHAR(100) NOT NULL,
	IS_ACTIVE TINYINT(1) DEFAULT 0,

	PRIMARY KEY (USER_ID))
ENGINE=MyISAM DEFAULT CHARACTER SET latin1
    COLLATE latin1_general_cs AUTO_INCRMENT=0;

CREATE TABLE WROX_PENDING (
	USER_ID INTEGER UNSIGNED NOT NULL,
	TOKEN CHAR(10) NOT NULL,
	CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

	FOREIGN KEY (USER_ID)
	    REFERENCES WORX_USER(USER_ID)
)
ENGINE=MyISAM DEFAULT CHARACTER SET latin1
    COLLATE latin1_general_cs;
